spring:
  jpa:
    # 전송 쿼리 확인
    # show-sql, format-sql옵션은 애플리케이션 실행 과정에 데이터베이스에 쿼리할 일이 있으면 실행 구문을 모두 보여주는 옵션.
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    # 테이블 생성 후에 data.sql 실행
    # defer-datasource-initialization 옵션은 애플리케이션을 실행할 때 테이블을 생성하고 data.sql 파일에 있는 쿼리를 실행하도록 하는 옵션.
    defer-datasource-initialization: true
  datasource: # 데이터베이스 정보 추가
    url: jdbc:h2:mem:testdb
    username: sa
  h2: # 콘솔 활성화
    console:
      enabled: true
jwt:
  issuer: ajufresh@gamil.com # 이슈 발급자
  secret_key: study-springboot # 비밀키



